import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local";

const madeMirage = localFont({
  src: "../public/fonts/made-mirage-regular.otf",
  variable: "--font-made-mirage",
  style: "normal",
});

export const metadata: Metadata = {
  title: "Blog",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${madeMirage.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
