import type { Metadata } from "next";
import "./globals.css";
import localfont from "next/font/local";

const madeMIrage = localfont({
  src: "../public/fonts/myfont.otf",
  variable: "--font-made-mirage",
  style: "regular",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${madeMIrage.variable} ${madeMIrage.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
